import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-inter'
})

export const metadata = {
  title: 'Meal | AI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-orange-400`}>
        {children}
      </body>
    </html>
  )
}
